In [1]:
L = [1243, 23, 34, -123]

In [2]:
L

[1243, 23, 34, -123]

In [3]:
import numpy as np

In [4]:
a = np.array(L)

In [5]:
a

array([1243,   23,   34, -123])

In [6]:
a.mean()

294.25

In [9]:
L.pop(2)

34

In [10]:
L

[1243, 23, -123]

In [11]:
a

array([1243,   23,   34, -123])

In [12]:
a[:]

array([1243,   23,   34, -123])

In [13]:
a[:3]

array([1243,   23,   34])

In [14]:
a[:-2]

array([1243,   23])

In [15]:
a

array([1243,   23,   34, -123])

In [16]:
b = a[:2]

In [17]:
b

array([1243,   23])

In [21]:
#Reflects at a
b[1] = 1001

In [19]:
b

array([1243, 1001])

In [20]:
a

array([1243, 1001,   34, -123])

In [22]:
#Won't override
c = a.copy()

In [23]:
c

array([1243, 1001,   34, -123])

In [24]:
c[1] = 2000

In [25]:
a

array([1243, 1001,   34, -123])

In [26]:
c

array([1243, 2000,   34, -123])